### ISSUE TITLE
Global search stopped working

### ISSUE THREAD

**Issue by mroovaa** [allejok96/plugin.video.jwb-unofficial#8]
Hello

I'm on Kodi 18.9, Ubuntu 18.04

Searching for any text gives an error, relevant info from the log file below:

2021-03-06 20:17:03.995 T:140122022299392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/home/marek/.kodi/addons/plugin.video.jwb-unofficial/addon.py", line 740, in <module>
                                                search_page()
                                              File "/home/marek/.kodi/addons/plugin.video.jwb-unofficial/addon.py", line 613, in search_page
                                                token = urlopen(token_url).read().decode('utf-8')
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--
2021-03-06 20:17:04.075 T:140122030692096   ERROR: GetDirectory - Error getting plugin://plugin.video.jwb-unofficial/?mode=search
2021-03-06 20:17:04.079 T:140125149599872   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jwb-unofficial/?mode=search) failed

**Comment by allejok96** [comment]
Thanks, it was using an address from the old tv.jw.org days...
